In [50]:
import pandas as pd
import matplotlib.pyplot as plt

In [51]:
df = pd.read_csv("survey_results_public.csv")

In [52]:
df.head(3)

Respondent                      MainBranch Hobbyist  Age Age1stCode  \
0           1  I am a developer by profession      Yes  NaN         13   
1           2  I am a developer by profession       No  NaN         19   
2           3     I code primarily as a hobby      Yes  NaN         15   

  CompFreq  CompTotal  ConvertedComp             Country    CurrencyDesc  ...  \
0  Monthly        NaN            NaN             Germany   European Euro  ...   
1      NaN        NaN            NaN      United Kingdom  Pound sterling  ...   
2      NaN        NaN            NaN  Russian Federation             NaN  ...   

                   SurveyEase           SurveyLength Trans  \
0  Neither easy nor difficult  Appropriate in length    No   
1                         NaN                    NaN   NaN   
2  Neither easy nor difficult  Appropriate in length   NaN   

                                      UndergradMajor WebframeDesireNextYear  \
0  Computer science, computer engineering, or sof...           ASP.NET Core   
1  Computer science, computer engineering, or sof...                    NaN   
2                                                NaN                    NaN   

     WebframeWorkedWith                             WelcomeChange WorkWeekHrs  \
0  ASP.NET;ASP.NET Core   Just as welcome now as I felt last year        50.0   
1                   NaN  Somewhat more welcome now than last year         NaN   
2                   NaN  Somewhat more welcome now than last year         NaN   

  YearsCode YearsCodePro  
0        36           27  
1         7            4  
2         4          NaN  

[3 rows x 61 columns]

In [53]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment", "ConvertedComp"]]
df = df.rename({"ConvertedComp": "Salary"}, axis=1)
df.head(3)

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   

  YearsCodePro                                         Employment  Salary  
0           27  Independent contractor, freelancer, or self-em...     NaN  
1            4                                 Employed full-time     NaN  
2          NaN                                                NaN     NaN

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       4999 non-null   object 
 1   EdLevel       4896 non-null   object 
 2   YearsCodePro  4155 non-null   object 
 3   Employment    4979 non-null   object 
 4   Salary        3453 non-null   float64
dtypes: float64(1), object(4)
memory usage: 195.4+ KB


In [55]:
df = df[df["Salary"].notnull()]
df.head(3)

Country                                          EdLevel  \
7    United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

   YearsCodePro          Employment    Salary  
7            13  Employed full-time  116000.0  
9             4  Employed full-time   32315.0  
10            2  Employed full-time   40070.0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3453 entries, 7 to 4998
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       3453 non-null   object 
 1   EdLevel       3414 non-null   object 
 2   YearsCodePro  3442 non-null   object 
 3   Employment    3451 non-null   object 
 4   Salary        3453 non-null   float64
dtypes: float64(1), object(4)
memory usage: 161.9+ KB


In [57]:
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
Employment      0
Salary          0
dtype: int64

In [58]:
df = df[df["Employment"] == "Employed full-time"]
df = df.drop("Employment", axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3052 entries, 7 to 4998
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       3052 non-null   object 
 1   EdLevel       3052 non-null   object 
 2   YearsCodePro  3052 non-null   object 
 3   Salary        3052 non-null   float64
dtypes: float64(1), object(3)
memory usage: 119.2+ KB


In [59]:
df['Country'].value_counts()

United States     1754
Canada             264
United Kingdom     164
Germany             97
Brazil              82
                  ... 
Sudan                1
Costa Rica           1
Saudi Arabia         1
Slovakia             1
Paraguay             1
Name: Country, Length: 94, dtype: int64

In [60]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'other'
    return categorical_map

In [63]:
country_map = shorten_categories(df.Country.value_counts(), 20)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

United States         1754
other                  323
Canada                 264
United Kingdom         164
Germany                 97
Brazil                  82
Australia               52
India                   52
France                  36
Poland                  31
Netherlands             31
Mexico                  29
Spain                   27
Italy                   24
Sweden                  24
Russian Federation      22
Ukraine                 20
Turkey                  20
Name: Country, dtype: int64

In [64]:
df = df[df["Salary"] <= 250000]
df = df[df["Salary"] >= 10000]
df = df[df["Salary"] != 'Other']

In [65]:
df["YearsCodePro"].unique()

array(['13', '4', '2', '7', '20', '1', '3', '10', '14', '12', '29', '6',
       '28', '8', '23', '15', '25', '5', '9', '11', 'Less than 1 year',
       '21', '16', '18', '32', '19', '22', '38', '30', '26', '17', '27',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44'], dtype=object)

In [66]:
def clean_experience(x):
    if x == 'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [67]:
df["EdLevel"].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)

In [68]:
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if "Master’s degree" in x:
        return "Master’s degree"
    if "Professional degree" in x or "Other doctoral" in x:
        return 'Post grad'
    return "Less than a Bachelors"

In [69]:
df['EdLevel'] = df['EdLevel'].apply(clean_education)

In [70]:
df["EdLevel"].unique()

array(['Bachelor’s degree', 'Master’s degree', 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [71]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df["EdLevel"] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()

array([0, 2, 1, 3])

In [72]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()

array([16, 15, 11,  8,  4,  2, 17,  6,  1,  3,  5,  7, 12, 13,  9,  0, 14,
       10])

In [73]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

In [74]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [75]:
y_pred = linear_reg.predict(X)

In [76]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))

In [77]:
error

42179.3401279516

In [78]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [79]:
y_pred = dec_tree_reg.predict(X)

In [82]:
error = np.sqrt(mean_squared_error(y, y_pred))
print(f"{error:.02f}")

29957.71


In [83]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=4)
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=4)

In [84]:
y_pred = random_forest_reg.predict(X)


In [85]:
error = np.sqrt(mean_squared_error(y, y_pred))
print(f"{error:.02f}")

30399.81


In [86]:
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2, 4, 6, 8, 10, 12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [88]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print(f"{error:.02f}")

33349.03


In [89]:
X

Country  EdLevel  YearsCodePro
7          16        0          13.0
9          15        2           4.0
10         15        0           2.0
11         11        1           7.0
12          8        1          20.0
...       ...      ...           ...
4983       16        0           8.0
4989       16        1          22.0
4993       16        0          26.0
4994        0        0           7.0
4998       16        1           9.0

[2746 rows x 3 columns]

In [95]:
X = np.array([["United States", "Master’s degree", 15]])
X

array([['United States', 'Master’s degree', '15']], dtype='<U21')

In [96]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[16.,  2., 15.]])

In [97]:
y_pred = regressor.predict(X)
y_pred

/home/mohsen/anaconda3/envs/streamlitEnv/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([150162.90990991])

In [98]:
import pickle 

In [100]:
data = {"model": regressor, "le_country": le_country, "le_education": le_education}

with open("saved_steps.pkl", 'wb') as file:  # write binary
    pickle.dump(data, file)

In [101]:
with open("saved_steps.pkl", 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]

In [102]:
y_pred = regressor_loaded.predict(X)
y_pred

/home/mohsen/anaconda3/envs/streamlitEnv/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([150162.90990991])

In [103]:
df.Country.value_counts()

16    1598
17     274
2      253
15     141
4       94
1       65
0       47
3       34
5       33
8       30
9       29
7       26
11      25
12      23
6       21
10      21
14      18
13      14
Name: Country, dtype: int64